name: PHP CLI
on:
  push:
    paths:
      - .trigger
      - .github/workflows/cli.yml
      - cli/**
    branches: [ "master" ]

jobs:
  cli:
    name: Build PHP images
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version:
          - from: "7.2.34-cli-buster"
            tag: "7.2"
          - from: "7.3.33-cli-bullseye"
            tag: "7.3"
          - from: "7.4.30-cli-bullseye"
            tag: "7.4"
          - from: "8.0.21-cli-bullseye"
            tag: "8.0"
          - from: "8.1.8-cli-bullseye"
            tag: "8.1"
          - from: "8.2.0alpha3-cli-bullseye"
            tag: "8.2"

    steps:
      - run: sudo chown runner:docker /var/run/docker.sock
        if: ${{ env.ACT }}

      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - uses: docker/build-push-action@v2
        with:
          context: cli
          platforms: linux/amd64,linux/arm64
          build-args: PHP_VERSION=${{ matrix.version.from }}
          push: ${{ github.ref == 'refs/heads/master' && !env.ACT }}
          tags: docker.io/rollupdev/php:${{ matrix.version.tag }}
