name: PHP CLI
on:
  schedule:
    - cron: "0 6 1 * *" # 6 AM UTC on 1st day of month
  push:
    paths:
      - .trigger
      - .github/workflows/cli.yml
      - cli/**
      - cli-loaders/**
    branches: [ "master" ]

jobs:
  cli:
    name: Build PHP images
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version:
          - from: "7.2-cli-buster"
            tag: "7.2"
          - from: "7.3-cli-bullseye"
            tag: "7.3"
          - from: "7.4-cli-bullseye"
            tag: "7.4"
          - from: "8.0-cli-bullseye"
            tag: "8.0"
          - from: "8.1-cli-bullseye"
            tag: "8.1"
          - from: "8.2-rc-cli-buster"
            tag: "8.2"

    steps:
      - name: Set up Actions
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: cli
          platforms: linux/amd64,linux/arm64
          build-args: PHP_VERSION=${{ matrix.version.from }}
          push: ${{ github.ref == 'refs/heads/master' && !env.ACT }}
          tags: docker.io/rollupdev/php:${{ matrix.version.tag }}
  cli-loaders:
    name: Build PHP images
    runs-on: ubuntu-latest
    needs: cli

    strategy:
      fail-fast: false
      matrix:
        version:
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"

    steps:
      - name: Set up Actions
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: cli-loaders
          platforms: linux/amd64,linux/arm64
          build-args: PHP_VERSION=${{ matrix.version }}
          push: ${{ github.ref == 'refs/heads/master' && !env.ACT }}
          tags: docker.io/rollupdev/php:${{ matrix.version }}-loaders
