name: PHP FPM
on:
  schedule:
    - cron: "0 6 1 * *" # 6 AM UTC on 1st day of month
  push:
    paths:
      - .trigger
      - .github/workflows/fpm.yml
      - fpm-loaders/**
      - fpm/**
    branches: [ "master" ]

jobs:
  fpm:
    name: Build PHP images
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version:
          - from: "7.2.34-fpm-buster"
            tag: "7.2"
          - from: "7.3.33-fpm-bullseye"
            tag: "7.3"
          - from: "7.4.30-fpm-bullseye"
            tag: "7.4"
          - from: "8.0.21-fpm-bullseye"
            tag: "8.0"
          - from: "8.1.8-fpm-bullseye"
            tag: "8.1"
          - from: "8.2.0alpha3-fpm-bullseye"
            tag: "8.2"
    steps:
      - name: Set up Actions
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: fpm
          platforms: linux/amd64,linux/arm64
          build-args: PHP_VERSION=${{ matrix.version.from }}
          push: ${{ github.ref == 'refs/heads/master' && !env.ACT }}
          tags: docker.io/rollupdev/php:${{ matrix.version.tag }}-fpm


  fpm-loaders:
    name: Build PHP images with Loaders
    runs-on: ubuntu-latest
    needs: fpm

    strategy:
      fail-fast: false
      matrix:
        version:
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"

    steps:
      - name: Set up Actions
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: fpm-loaders
          platforms: linux/amd64,linux/arm64
          build-args: PHP_VERSION=${{ matrix.version }}
          push: ${{ github.ref == 'refs/heads/master' && !env.ACT }}
          tags: docker.io/rollupdev/php:${{ matrix.version }}-fpm-loaders
